fragment BayaanFields on Bayaan {
   sys {
      id
   }
   title
   slug
   description
   masjid
   metaTitle
   metaDescription
   event
   date
   author
   duration
   category
   geoLink
   audio {
      ...AssetsFields
   }
}