fragment BayaanFields on Bayaan {
   sys {
      id
   }
   title
   slug
   description
   metaTitle
   metaDescription
   event
   date
   author
   duration
   category
   masjid {
      title
      geoLink
   }
   audio {
      ...AssetsFields
   }
}