query GetBayaan (
  $startDate: DateTime, 
  $endDate: DateTime, 
  $search: String, 
  # $categories: [String],
  $limit: Int, 
  $skip: Int
) {
  bayaanCollection (
    where: {
      date_gte: $startDate,
      date_lte: $endDate,
      title_contains: $search,
      # category_in: $categories,
    },
    limit: $limit, 
    skip: $skip,
    order: date_DESC
  ) {
    total
    items {
      sys {
        id
      }
      title
      description
      masjid
      metaTitle
      metaDescription
      author
      date
      tag
      audio {
        ...AssetsFields
      }
    }
  }
}