query relatedBayaan($currentSlug: String, $event: String, $date_gte: DateTime, $date_lt: DateTime,  $category: [String], $limit: Int, $skip: Int) {
   event: bayaanCollection(where: { slug_not: $currentSlug, event_contains: $event, date_gte: $date_gte, date_lt: $date_lt }, limit: $limit){
      total
      items {
         ...BayaanFields
      }
	}
  
   category: bayaanCollection(where: { slug_not: $currentSlug, category_contains_some: $category}, limit: $limit){
      total
      items {
         ...BayaanFields
      }
	}

   random: bayaanCollection(where: { slug_not: $currentSlug } ,limit: $limit, skip: $skip) {
      total
      items {
         ...BayaanFields
      }
   }
}