query relatedBayaan($currentSlug: String, $event: String, $date_gte: DateTime, $date_lt: DateTime,  $category: [String], $skip: Int) {
   event: bayaanCollection(where: { slug_not: $currentSlug, event: $event, date_gte: $date_gte, date_lt: $date_lt }, limit: 4){
      total
      items {
         ...BayaanFields
      }
	}
  
   category: bayaanCollection(where: { slug_not: $currentSlug, category_contains_some: $category}, limit: 4){
      total
      items {
         ...BayaanFields
      }
	}

   random: bayaanCollection(where: { slug_not: $currentSlug } ,limit: 4, skip: $skip) {
      total
      items {
         ...BayaanFields
      }
   }
}