import type { Metadata } from "next";
import { NextUiProvider } from "./providers";

import "./styles/bootstrap-grid/bootstrap-grid.min.css";
import "./styles/globals.css";

import localFont from 'next/font/local';


const Objektiv = localFont({
  src: [
    {
      path: './fonts/objektivmk3_regular.woff2',
      weight: '400',
      style: 'normal',
      
    },
    {
      path: './fonts/objektivmk3_regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/objektivmk3_bold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/objektivmk3_bold.woff',
      weight: '600',
      style: 'normal',
    }
  ],
  preload: true,
  display: 'swap'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={Objektiv.className}>
        <NextUiProvider>
          {children}
        </NextUiProvider>
      </body>
    </html>
  );
}
